name: test_softcent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  flutter_staggered_grid_view: ^0.6.1
  get: 4.6.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  persistent_bottom_nav_bar: ^4.0.2
  flutter_typeahead: ^3.2.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/png/

